# Generated by Django 4.2.5 on 2023-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_pupil_bio_alter_teacher_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='lessons',
            field=models.ManyToManyField(related_name='pupils', to='profiles.lesson'),
        ),
    ]
