# Generated by Django 4.2.5 on 2023-10-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_pupil_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
