# Generated by Django 4.2.5 on 2023-09-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('begona', 'begona'), ('admin', 'admin'), ('teacher', 'teacher'), ('pupil', 'pupil')], default='begona', max_length=10),
        ),
    ]
