# Generated by Django 4.2.5 on 2023-09-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_photo_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('begona', 'begona'), ('admin', 'admin'), ('teacher', 'teacher'), ('pupil', 'pupil')], default='begona', max_length=10, unique=True),
        ),
    ]
